repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
    exclude: .devcontainer/devcontainer.json
  - id: check-yaml
  - id: check-xml
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.4
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
  - id: mypy
    additional_dependencies: [types-PyYAML]
