<user.letter_key>: key(letter_key)
<user.symbol_key>: key(symbol_key)
<user.special_key>: key(special_key)
go <user.arrow_key>: key(arrow_key)
<user.modifier_keys> <user.unmodified_key>: key("{modifier_keys}-{unmodified_key}")
press <user.modifier_keys>: key(modifier_keys)
<user.function_key>: key(function_key)
